# Generated by Django 3.1.2 on 2020-10-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201016_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.user')),
            ],
        ),
    ]
